# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 07:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsroom_app.Article'),
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='field',
            field=models.ManyToManyField(to='newsroom_app.Field'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
