# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom_app', '0003_auto_20170413_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='style',
            name='color',
        ),
        migrations.RemoveField(
            model_name='style',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='style',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='style',
            name='height',
        ),
        migrations.RemoveField(
            model_name='style',
            name='text_align',
        ),
        migrations.RemoveField(
            model_name='style',
            name='width',
        ),
        migrations.AddField(
            model_name='style',
            name='name',
            field=models.CharField(default='color', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stylevalue',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsroom_app.Style'),
        ),
    ]
