# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom_app', '0005_stylevalue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='style',
            field=models.ManyToManyField(blank=True, null=True, to='newsroom_app.StyleValue'),
        ),
    ]
