# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom_app', '0006_auto_20170413_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontent',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
